export default {
  Union: [{ name: "Union Station", id: "UN" }],
  "Union Pearson": [{ name: "Pearson Airport", id: "PE" }],
  "Lakeshore East": [
    { name: "Whitby", id: "WH" },
    { name: "Ajax", id: "AJ" },
    { name: "Pickering", id: "PI" },
    { name: "Rouge Hill", id: "RO" },
    { name: "Guildwood", id: "GU" },
    { name: "Eglinton", id: "EG" },
    { name: "Scarborough", id: "SC" },
    { name: "Danforth", id: "DA" },
  ],
  Stouffville: [
    { name: "Old Elm", id: "LI" },
    { name: "Stouffville", id: "ST" },
    { name: "Mount Joy", id: "MJ" },
    { name: "Markham", id: "MR" },
    { name: "Centennial", id: "CE" },
    { name: "Unionville", id: "UI" },
    { name: "Milliken", id: "MK" },
    { name: "Agincourt", id: "AG" },
    { name: "Kennedy", id: "KE" },
  ],
  "Richmond Hill": [
    { name: "Bloomington", id: "BM" },
    { name: "Gormley", id: "GO" },
    { name: "Richmond Hill", id: "RI" },
    { name: "Langstaff", id: "LA" },
    { name: "Old Cummer", id: "OL" },
    { name: "Oriole", id: "OR" },
  ],
  Barrie: [
    { name: "Allendale Waterfront", id: "AD" },
    { name: "Barrie South", id: "BA" },
    { name: "Bradford", id: "BD" },
    { name: "East Gwillimbury", id: "EA" },
    { name: "Newmarket", id: "NE" },
    { name: "Aurora", id: "AU" },
    { name: "King City", id: "KC" },
    { name: "Maple", id: "MP" },
    { name: "Rutherford", id: "RU" },
    { name: "Downsview Park", id: "DO" },
  ],
  "Lakeshore West": [
    { name: "Exhibition", id: "EX" },
    { name: "Mimico", id: "MI" },
    { name: "Long Branch", id: "LO" },
    { name: "Port Credit", id: "PO" },
    { name: "Clarkson", id: "CL" },
    { name: "Oakville", id: "OA" },
    { name: "Bronte", id: "BO" },
    { name: "Appleby", id: "AP" },
    { name: "Burlington", id: "BU" },
    { name: "Aldershot", id: "AL" },
    { name: "Hamilton", id: "HA" },
    { name: "West Harbour", id: "WR" },
    { name: "St. Catharines", id: "SCTH" },
    { name: "Niagara Falls", id: "NI" },
  ],
  Milton: [
    { name: "Kipling", id: "KP" },
    { name: "Dixie", id: "DI" },
    { name: "Cooksville", id: "CO" },
    { name: "Erindale", id: "ER" },
    { name: "Streetsville", id: "SR" },
    { name: "Meadowvale", id: "ME" },
    { name: "Lisgar", id: "LS" },
    { name: "Milton", id: "ML" },
  ],
  Kitchener: [
    { name: "Bloor", id: "BL" },
    { name: "Weston", id: "WE" },
    { name: "Etobicoke North", id: "ET" },
    { name: "Malton", id: "MA" },
    { name: "Bramalea", id: "BE" },
    { name: "Brampton", id: "BR" },
    { name: "Mount Pleasant", id: "MO" },
    { name: "Georgetown", id: "GE" },
    { name: "Acton", id: "AC" },
    { name: "Guelph Central", id: "GL" },
    { name: "Kitchener", id: "KI" },
  ],
};
